### ISSUE TITLE
Notice of Copyright Violation

### ISSUE THREAD

**Issue by Iconoclasta** [poseidondev/posq#7]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitly exclude the PIVX developers from all copyrights.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution time frame commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA take-down notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository.

File in question:

      posq/LICENSE

**Comment by arkit3kt** [comment]
Hello, just saw your issue. Edited the file in question, will take a look through more files in the coming days.

**Comment by Fuzzbawls** [comment]
@arkit3kt should really just remove the `LICENSE` file entirely, unless your intention is to sublicense your fork under a **non**-MIT license. 

The existing `COPYING` file serves the purpose of the MIT license and would be compliant on it's own.

**Comment by arkit3kt** [comment]
thanks @Fuzzbawls , will go ahead and remove it now

**Comment by Iconoclasta** [comment]
Everything seems in order. We'll double check a few more of your source files and confirm your compliance.

**Comment by arkit3kt** [comment]
I see there's been no response for nearly a week, closing this. Open a new one if needed, thanks.

**Comment by Iconoclasta** [comment]
Everything seems in order. Thanks for the collaboration.
